[package]
name = "default-audio-switcher"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = { version = "0.22.2", default-features = false, features = ["playback", "wav"] }
hound = "3.5.1"

[dependencies.windows]
version = "0.62.2"
features = [
	"Win32_System_Com",
	"Win32_Media",
	"Win32_Media_Audio",
	"Win32_UI_Shell_PropertiesSystem",
	"Win32_Devices",
	"Win32_Devices_FunctionDiscovery",
]